/*
 * Copyright (c) 2026. Tony Finnerty
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package com.tfcode.comparetout.model.ops;

import com.tfcode.comparetout.model.ScenarioDAO;
import com.tfcode.comparetout.model.ToutcDB;
import com.tfcode.comparetout.model.dao.PanelDAO;
import com.tfcode.comparetout.model.scenario.Panel;
import com.tfcode.comparetout.model.scenario.Scenario;
import com.tfcode.comparetout.model.scenario.Scenario2Panel;

import java.util.List;

/**
 * Panel orchestration, moved verbatim from ScenarioDAO's concrete
 * {@code @Transaction} methods (mega-refactor C6). Each body is the original
 * wrapped in {@code db.runInTransaction} — identical atomicity.
 * linkPanelFromScenario stays on ScenarioDAO until C9 (called by the
 * cross-domain linkAllComponentsFromScenario); copyPanelData and getPanelForID
 * also stay on ScenarioDAO (lifecycle/direct-consumer), so the copy ops call
 * them via scenarioDAO.
 */
public class PanelOps {

    private final ToutcDB db;
    private final ScenarioDAO scenarioDAO;
    private final PanelDAO panelDAO;

    public PanelOps(ToutcDB db) {
        this.db = db;
        this.scenarioDAO = db.scenarioDAO();
        this.panelDAO = db.panelDAO();
    }

    public void deletePanelFromScenario(Long panelID, Long scenarioID) {
        db.runInTransaction(() -> {
            panelDAO.removeScenario2Panel(panelID, scenarioID);
            scenarioDAO.deleteOrphanPanels();
            scenarioDAO.deleteOrphanPanelData();
            List<Panel> panels = scenarioDAO.getPanelsForScenarioID(scenarioID);
            if (panels.isEmpty()) {
                Scenario scenario = scenarioDAO.getScenario(scenarioID);
                scenario.setHasPanels(false);
                scenarioDAO.updateScenario(scenario);
            }
        });
    }

    public long savePanel(Long scenarioID, Panel panel) {
        final long[] result = new long[1];
        db.runInTransaction(() -> {
            long panelID = panel.getPanelIndex();
            if (panelID == 0) {
                panelID = scenarioDAO.addNewPanels(panel);
                Scenario2Panel s2p = new Scenario2Panel();
                s2p.setScenarioID(scenarioID);
                s2p.setPanelID(panelID);
                scenarioDAO.addNewScenario2Panel(s2p);

                // Guard against a bad scenarioID (e.g. a failed scenario insert returning 0): never NPE here.
                Scenario scenario = scenarioDAO.getScenario(scenarioID);
                if (scenario != null) {
                    scenario.setHasPanels(true);
                    scenarioDAO.updateScenario(scenario);
                }
            }
            else {
                panelDAO.updatePanel(panel);
            }
            result[0] = panelID;
        });
        return result[0];
    }

    public void copyPanelFromScenario(long fromScenarioID, Long toScenarioID) {
        db.runInTransaction(() -> {
            List<Panel> panels = scenarioDAO.getPanelsForScenarioID(fromScenarioID);
            for (Panel panel: panels) {
                long oldPanelID = panel.getPanelIndex();
                panel.setPanelIndex(0L);
                long newPanelID = scenarioDAO.addNewPanels(panel);

                Scenario2Panel s2p = new Scenario2Panel();
                s2p.setScenarioID(toScenarioID);
                s2p.setPanelID(newPanelID);
                scenarioDAO.addNewScenario2Panel(s2p);

                Scenario toScenario = scenarioDAO.getScenario(toScenarioID);
                toScenario.setHasPanels(true);
                scenarioDAO.updateScenario(toScenario);
                scenarioDAO.copyPanelData(oldPanelID, newPanelID);
            }

            scenarioDAO.deleteOrphanPanels();
        });
    }

    /**
     * Link <b>one</b> panel to a scenario, idempotently. The Directors tab shares panels per-string, but the
     * scenario-level linkPanelFromScenario links <i>every</i> panel of the source and {@code scenario2panel}
     * has an autogenerated PK with no unique (scenarioID, panelID) constraint — so re-linking duplicated the
     * junction row, and the sim (which iterates the rows) then double-counted the PV. This guards against that:
     * nothing happens if the link already exists.
     */
    public void linkPanelToScenario(long panelID, long scenarioID) {
        db.runInTransaction(() -> {
            if (panelDAO.countPanelLink(scenarioID, panelID) > 0) return;
            Scenario2Panel s2p = new Scenario2Panel();
            s2p.setScenarioID(scenarioID);
            s2p.setPanelID(panelID);
            scenarioDAO.addNewScenario2Panel(s2p);
            Scenario scenario = scenarioDAO.getScenario(scenarioID);
            if (scenario != null) {
                scenario.setHasPanels(true);
                scenarioDAO.updateScenario(scenario);
            }
        });
    }

    /** Copy <b>one</b> panel (fresh id) and its generated data onto a scenario — the per-string FORK for the
     *  Directors tab (the scenario-level copyPanelFromScenario copies every panel of the source). */
    public void copyPanelToScenario(long panelID, long scenarioID) {
        db.runInTransaction(() -> {
            Panel panel = scenarioDAO.getPanelForID(panelID);
            if (panel == null) return;
            panel.setPanelIndex(0L);
            long newPanelID = scenarioDAO.addNewPanels(panel);
            Scenario2Panel s2p = new Scenario2Panel();
            s2p.setScenarioID(scenarioID);
            s2p.setPanelID(newPanelID);
            scenarioDAO.addNewScenario2Panel(s2p);
            Scenario scenario = scenarioDAO.getScenario(scenarioID);
            if (scenario != null) {
                scenario.setHasPanels(true);
                scenarioDAO.updateScenario(scenario);
            }
            scenarioDAO.copyPanelData(panelID, newPanelID);
            scenarioDAO.deleteOrphanPanels();
        });
    }
}
