/*
 * Copyright (c) 2023-2024. Tony Finnerty
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package com.tfcode.comparetout.model;

import androidx.lifecycle.LiveData;
import androidx.room.Dao;
import androidx.room.Insert;
import androidx.room.Query;

import com.tfcode.comparetout.model.costings.Costings;

import java.util.List;

/**
 * Data Access Object for managing electricity cost calculations and comparisons.
 * <p>
 * This DAO handles the storage and retrieval of cost analysis results generated by
 * applying different price plans to energy usage scenarios. It provides methods for
 * finding optimal pricing strategies and maintaining data consistency as price plans
 * and scenarios change.
 * <p>
 * Key functionality:
 * - Store cost calculation results for scenario/price plan combinations
 * - Find best (lowest cost) pricing options for scenarios
 * - Export cost comparison data for analysis
 * - Maintain referential integrity with price plan deletions
 * - Check existence of calculations to avoid duplicate processing
 * <p>
 * Cost calculations include:
 * - Net cost (total cost after buy/sell transactions)
 * - Buy costs (electricity purchased from grid)
 * - Sell income (electricity sold to grid)
 * - Standing charges and signup bonuses
 */
@Dao
public abstract class CostingDAO {

    /**
     * Load all cost calculation results for reactive UI display.
     * @return LiveData list of all Costings records
     */
    @Query("SELECT * FROM costings")
    public abstract LiveData<List<Costings>> loadCostings();

    /**
     * Save a cost calculation result to the database.
     * @param costing The Costings record to insert
     */
    @Insert
    public abstract void saveCosting(Costings costing);

    /**
     * Delete all cost calculations associated with a specific price plan.
     * Called when a price plan is deleted to maintain referential integrity.
     * <p>
     * Matches BOTH key columns: a plan id can appear as the import side or, for
     * an export plan, as the export side. Matching only {@code pricePlanID} would
     * strand every pair row that referenced a deleted export plan, and the
     * Compare tab would show ghost pairings until a later prune.
     * @param id The plan id, on either side of the pairing
     */
    @Query("DELETE FROM costings WHERE pricePlanID = :id OR exportPlanID = :id")
    public abstract void deleteRelatedCostings(int id);

    /** Wipe all costings (one-time paneldata rollout refresh — they recompute after re-simulation). */
    @Query("DELETE FROM costings")
    public abstract void deleteAllCostings();

    /**
     * Find the most cost-effective price plan for a given scenario, ignoring any
     * costing whose plan no longer exists.
     * <p>
     * The existence tests are load-bearing, not defensive tidying. The schema
     * declares no foreign keys, so deleting a {@code PricePlans} row leaves its
     * {@code costings} rows behind until something prunes them — and the prune is
     * a separate task on {@code databaseWriteExecutor}, an 8-thread pool with no
     * ordering barrier. A dashboard read that lands in that window would
     * otherwise return the orphan and cache it, leaving "Best Cost/Year" naming a
     * plan the user just deleted (plans/bugs/plan.md §2).
     * <p>
     * {@code exportPlanID = 0} is the bundled-export sentinel, not a plan id, so
     * it is excluded from the test before the lookup — the same carve-out
     * {@link #pruneCostings()} makes. Without it every IE row, where export is a
     * bundled rate rather than a separate contract, would be filtered out.
     * <p>
     * {@code ORDER BY net ASC LIMIT 1} replaces the old {@code MIN(net)}
     * subquery: one scan instead of two, and it cannot return two rows on a tie.
     *
     * @param scenarioID The scenario to find the best costing for
     * @return The lowest-net costing whose plans still exist, or null if none do
     */
    @Query("SELECT * FROM costings " +
            "WHERE scenarioID = :scenarioID " +
            "  AND pricePlanID IN (SELECT pricePlanIndex FROM PricePlans) " +
            "  AND (exportPlanID = 0 " +
            "       OR exportPlanID IN (SELECT pricePlanIndex FROM PricePlans)) " +
            "ORDER BY net ASC LIMIT 1")
    public abstract Costings getBestCostingForScenario(Long scenarioID);

    @Query("SELECT * FROM costings WHERE scenarioID = :scenarioID ORDER BY net ASC")
    public abstract List<Costings> getAllCostingsForScenario(Long scenarioID);

    /**
     * Check if a cost calculation already exists for a scenario/price plan combination.
     * Used to avoid duplicate calculations and improve performance.
     * <p>
     * Query: SELECT EXISTS (SELECT * FROM costings WHERE scenarioID = :scenarioID AND pricePlanId = :pricePlanIndex)
     * 
     * @param scenarioID The scenario ID to check
     * @param pricePlanIndex The price plan ID to check
     * @return true if a costing record exists for this combination
     */
    @Query("SELECT EXISTS (SELECT * FROM costings WHERE scenarioID = :scenarioID " +
            "AND pricePlanId = :pricePlanIndex AND exportPlanID = :exportPlanIndex) AS OK")
    public abstract boolean costingExists(long scenarioID, long pricePlanIndex,
                                          long exportPlanIndex);

    /**
     * Export all cost comparison data in CSV-ready format.
     * <p>
     * Query: SELECT DISTINCT REPLACE(scenarioName, ',', ';') || ', ' || fullPlanName || ', ' || 
     *               net || ', ' || buy || ', ' || sell || ', ' || standingCharges || ', ' || signUpBonus
     *        FROM costings, PricePlans WHERE pricePlanIndex = pricePlanID
     * <p>
     * This complex query:
     * 1. JOINs costings with PricePlans to get plan details
     * 2. Concatenates all relevant fields into a single CSV line
     * 3. Replaces commas in scenario names with semicolons to prevent CSV parsing issues
     * 4. Uses DISTINCT to avoid duplicate entries
     * <p>
     * The result format is: ScenarioName, PlanName, NetCost, BuyCost, SellIncome, StandingCharges, SignupBonus
     * 
     * @return List of CSV-formatted strings for export
     */
    @Query("SELECT DISTINCT REPLACE(scenarioName, ',', ';') || ', ' || fullPlanName || ', ' || net || ', ' || buy || ', ' || sell || ', ' || " +
            "standingCharges || ', ' || signUpBonus AS line FROM costings, PricePlans WHERE pricePlanIndex = pricePlanID")
    public abstract List<String> getAllComparisonsNow();

    /**
     * Remove orphaned cost calculations that reference deleted price plans.
     * <p>
     * Query: DELETE FROM costings WHERE pricePlanId NOT IN (SELECT pricePlanIndex FROM PricePlans)
     * <p>
     * This maintenance query removes any costing records that reference price plans
     * that have been deleted, ensuring referential integrity. The NOT IN subquery
     * identifies costings with foreign keys that no longer have corresponding
     * parent records in the PricePlans table.
     * <p>
     * The second clause covers the export side of a pair. {@code exportPlanID = 0}
     * is the bundled sentinel, not a plan id, so it is excluded before the
     * existence test — otherwise every legacy row would be pruned on sight.
     */
    @Query("DELETE FROM costings " +
            "WHERE pricePlanId NOT IN (SELECT pricePlanIndex FROM PricePlans) " +
            "   OR (exportPlanID != 0 " +
            "       AND exportPlanID NOT IN (SELECT pricePlanIndex FROM PricePlans))")
    public abstract void pruneCostings();
}
